apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
      - name: my-spring-app
        image: fra.ocir.io/frupyqaukyoc/kolokvij:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: my-spring-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: my-spring-app
  type: LoadBalancer

